language: node_js
node_js: 10

# cache:
#   directories:
#     - node_modules

install:
  - npm cache verify
  - npm install

script:
  - ./node_modules/.bin/webpack --mode development
  - npm test

branches:
  only:
    - master