language: node_js
node_js: stable

cache:
  directories:
    - node_modules

install:
  - npm cache verify
  - npm install

script:
  - ./node_modules/.bin/webpack --mode development
  - npm test

branches:
  only:
    - master